sudo: false
language: go
go:
- 1.9.2
cache:
  directories:
  - vendor
install:
- make dep
script:
- make test clean
after_success:
- make build
branches:
  only:
  - master
addons:
  artifacts:
    paths:
    - $(git ls-files -o | grep .tar.gz | tr "\n" ":")
    debug: true
    s3_region: eu-west-1
    s3_bucket: remerge-artifacts
    target_paths: "$TRAVIS_REPO_SLUG"
